//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerprintAuthentication.Commons.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FingerprintAuthentication.Commons.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome do usuário.
        /// </summary>
        public static string USER001 {
            get {
                return ResourceManager.GetString("USER001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ter, pelo menos, 3 caracteres..
        /// </summary>
        public static string USER002 {
            get {
                return ResourceManager.GetString("USER002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o login do usuário.
        /// </summary>
        public static string USER003 {
            get {
                return ResourceManager.GetString("USER003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login do usuário deve ter exatamente 5 dígitos..
        /// </summary>
        public static string USER004 {
            get {
                return ResourceManager.GetString("USER004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a senha do usuário..
        /// </summary>
        public static string USER005 {
            get {
                return ResourceManager.GetString("USER005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não pode se chamar &quot;MASTER&quot;.
        /// </summary>
        public static string USER006 {
            get {
                return ResourceManager.GetString("USER006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não pode ter login &quot;00000&quot;.
        /// </summary>
        public static string USER007 {
            get {
                return ResourceManager.GetString("USER007", resourceCulture);
            }
        }
    }
}
